### ISSUE TITLE
Version number incorrect?

### ISSUE THREAD

**Issue by T4ESamuel** [Tools4everBV/HelloID-Conn-Prov-Source-Visma.net-HRM-API#18]
https://github.com/Tools4everBV/HelloID-Conn-Prov-Source-Visma.net-HRM-API/blob/27ce5d9ddaad4f9322f3c3511cd6dcd93e190884/persons.ps1#L4C2-L4C2

The connector version has been updated to version 3.1.0, but the scripts (both person and department script) remain versioned at 3.0.0.
Can this be updated to the latest version?

**Comment by JeroenBL** [comment]
updated in both scripts.
